// <auto-generated />
using System;
using ERPComercial.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPComercial.Infraestrutura.Migrations
{
    [DbContext(typeof(ErpContexto))]
    [Migration("20260708200505_AdicionandoModuloFinanceiro")]
    partial class AdicionandoModuloFinanceiro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoCliente"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoCliente");

                    b.ToTable("tb_clientes", (string)null);
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.ContaAReceber", b =>
                {
                    b.Property<int>("CodigoContaReceber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoContaReceber"));

                    b.Property<int>("ClienteCodigoCliente")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDeRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodigoContaReceber");

                    b.HasIndex("ClienteCodigoCliente");

                    b.ToTable("tb_contas_a_receber", (string)null);
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.Fornecedor", b =>
                {
                    b.Property<int>("CodigoFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoFornecedor"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoFornecedor");

                    b.ToTable("tb_fornecedores", (string)null);
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.ItemVenda", b =>
                {
                    b.Property<int>("CodigoItemVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoItemVenda"));

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoVenda")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaCodigoVenda")
                        .HasColumnType("int");

                    b.HasKey("CodigoItemVenda");

                    b.HasIndex("CodigoProduto");

                    b.HasIndex("VendaCodigoVenda");

                    b.ToTable("tb_itens_venda", (string)null);
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProduto"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoDeCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoDeVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEmEstoque")
                        .HasColumnType("int");

                    b.HasKey("CodigoProduto");

                    b.ToTable("tb_produtos", (string)null);
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.Venda", b =>
                {
                    b.Property<int>("CodigoVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoVenda"));

                    b.Property<int>("ClienteCodigoCliente")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDaVenda")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodigoVenda");

                    b.HasIndex("ClienteCodigoCliente");

                    b.ToTable("tb_vendas", (string)null);
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.ContaAReceber", b =>
                {
                    b.HasOne("ERPComercial.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCodigoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.ItemVenda", b =>
                {
                    b.HasOne("ERPComercial.Dominio.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPComercial.Dominio.Entidades.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaCodigoVenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.Venda", b =>
                {
                    b.HasOne("ERPComercial.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCodigoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ERPComercial.Dominio.Entidades.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
